import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import Navbar from "./Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Latihan Dasar Kepemimpinan | Kelompok 4</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <div className="flex justify-between flex-row w-full h-screen bg-gray-900 px-8 py-28">
        <div>
          <p className="text-4xl lg:text-5xl font-bold text-gray-900 dark:text-gray-100">
            Latihan Dasar Kepemimpinan <br />
          </p>
          <span className="text-gray-900 dark:text-gray-100 mt-3 font-bold text-4xl lg:text-5xl">
            Kelompok 4
          </span>
          <p className="text-xl text-gray-700 dark:text-gray-300 max-w-xl mt-3">
            Website ini adalah laporan kegiatan dari kegiatan Laporan Dasar
            Kepemimpinan yang sudah kami lakukan.
          </p>
        </div>
        <Image src="/1.jpeg" width={600} height={300} alt="ok" />
      </div>
      <div className="flex justify-between flex-row w-full h-screen bg-gray-900 px-8 py-28">
        <Image src="/2.jpeg" width={600} height={260} alt="ok" />
        <div>
          <p className="text-4xl lg:text-5xl font-bold text-gray-900 dark:text-gray-100">
            Latar Belakang
          </p>
          <p className="text-xl text-gray-700 dark:text-gray-300 max-w-2xl mt-3">
            Kebanyakan siswa-siswi tidak mengerti tentang kepemimpinan. Jadi
            agar bisa mengerti tentang memimpin, diadakanla kegiatan yang
            bernama LDK (Latihan Dasar Kepemimpinan)
          </p>
        </div>
      </div>
      <div className="flex justify-between flex-row w-full h-screen bg-gray-900 px-8 py-28">
        <div>
          <p className="text-4xl lg:text-5xl font-bold text-gray-900 max-w-xl dark:text-gray-100">
            Tujuan dari kegiatan Latihan Dasar Kepemimpinan (LDK)
          </p>
          <p className="text-xl text-gray-700 dark:text-gray-300 max-w-xl mt-3">
            Kegiatan ini ditujukan untuk para remaja, dapat mengerti lebih
            tentang kepemimpinan
          </p>
        </div>
        <Image src="/3.jpeg" width={600} height={300} alt="ok" />
      </div>
      <div className="flex justify-start gap-6 flex-row w-full h-screen bg-gray-900 px-8 py-16">
        <h2 className="text-gray-900 dark:text-gray-100 text-2xl font-bold">
          Waktu dan Tempat
        </h2>
        <ol className="relative border-l border-gray-200 dark:border-gray-700">
          <li className="mb-10 ml-4">
            <div className="absolute w-3 h-3 bg-gray-200 rounded-full mt-1.5 -left-1.5 border border-white dark:border-gray-900 dark:bg-gray-700" />
            <time className="mb-1 text-sm font-normal leading-none text-gray-400 dark:text-gray-500">
              10.30 - 12.00
            </time>
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
              Seminar tentang kepemimpinan: Be a leader not a follower
            </h3>
            <p className="mb-4 text-base font-normal text-gray-500 dark:text-gray-400">
              Di Aula Lantai 4 Candle Tree School
            </p>
          </li>
          <li className="mb-10 ml-4">
            <div className="absolute w-3 h-3 bg-gray-200 rounded-full mt-1.5 -left-1.5 border border-white dark:border-gray-900 dark:bg-gray-700" />
            <time className="mb-1 text-sm font-normal leading-none text-gray-400 dark:text-gray-500">
              10.00 - 10.30
            </time>
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
              Istirahat & Ganti Baju
            </h3>
            <p className="text-base font-normal text-gray-500 dark:text-gray-400">
              Gedung SMP Candle Tree
            </p>
          </li>
          <li className="ml-4">
            <div className="absolute w-3 h-3 bg-gray-200 rounded-full mt-1.5 -left-1.5 border border-white dark:border-gray-900 dark:bg-gray-700" />
            <time className="mb-1 text-sm font-normal leading-none text-gray-400 dark:text-gray-500">
              07.00 - 10.00
            </time>
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
              Renungan Bersama, Kata Sambutan dan Games
            </h3>
            <p className="text-base font-normal text-gray-500 dark:text-gray-400">
              Lapangan Indoor Candle Tree School
            </p>
          </li>
        </ol>
      </div>
    </div>
  );
}
