import React from "react";
import Image from "next/image";
import Head from "next/head";
import Navbar from "./Navbar";

const materi = () => {
  return (
    <>
      <Head>
        <title>Materi LDK | Kelompok 4</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="flex justify-between flex-row w-full h-screen bg-gray-900 px-8 py-28">
        <div>
          <p className="text-4xl lg:text-5xl font-bold text-gray-900 dark:text-gray-100">
            Materi Latihan Dasar Kepemimpinan (LDK) <br />
          </p>
          <p className="text-xl text-gray-700 dark:text-gray-300 max-w-xl mt-3">
            Di kegiatan LDK ini, terdapat dua sesi. Sesi pertama berada di
            lapangan Indoor. Di sesi pertama, kami bermain semua game. Tetapi di
            game tersebut terdapat berbagai manfaat dalam mengembangkan sikap
            kepemimpinan.
          </p>
        </div>
        <Image src="/4.jpeg" width={680} height={300} alt="ok" />
      </div>
      <div className="flex justify-between gap-12  flex-row w-full h-screen bg-gray-900 px-8 py-28">
        <Image src="/6.jpeg" width={750} height={300} alt="ok" />
        <div>
          <p className="text-4xl lg:text-5xl font-bold text-gray-900 max-w-2xl dark:text-gray-100">
            Sesi 1
          </p>
          <div className="text-xl text-gray-700 dark:text-gray-300 max-w-xl mt-3">
            <ul className="list-disc list">
              <p className="text-gray-900 dark:text-gray-100 font-semibold">
                Game-game yang kami mainkan di sesi 1 antara lain:
              </p>
              <li>Ganjil Genap</li>
              <li>Pancasila</li>
              <li>Pohon dan Tupai</li>
              <li>Benang Kusut</li>
              <li>
                Pos A (membawa bola dengan papan tanpa menyentuh hula-hop)
              </li>
              <li>Pos B (memindahkan bola dengan sumpit)</li>
              <li>Pos C (memindahkan bola dengan pipa)</li>
            </ul>
          </div>
        </div>
      </div>
      <div className="flex justify-between flex-row w-full h-screen bg-gray-900 px-8 py-28">
        <div>
          <p className="text-4xl lg:text-5xl font-bold text-gray-900 dark:text-gray-100">
            Sesi 1: Renungan Bersama
          </p>
          <p className="text-xl text-gray-700 dark:text-gray-300 max-w-xl mt-3">
            Sebelum memulai kegiatan dan games kami, kami mengawalinya dengan
            renungan bersama. Dengan melakukan renungan bersama, kami bisa
            mendapat materi rohani yang tentunya bermanfaat bagi kehidupan kami,
            juga materi kepemimpinan yang kami lakukan setelahnya
          </p>
        </div>
        <Image src="/5.jpeg" width={680} height={300} alt="ok" />
      </div>
      <div className="flex justify-between gap-12  flex-row w-full h-screen bg-gray-900 px-8 py-28">
        <Image src="/7.jpeg" width={750} height={300} alt="ok" />
        <div>
          <p className="text-4xl lg:text-5xl font-bold text-gray-900 max-w-2xl dark:text-gray-100">
            Sesi 2
          </p>
          <div className="text-xl text-gray-700 dark:text-gray-300 max-w-xl mt-3">
            <p className="text-xl text-gray-700 dark:text-gray-300 max-w-xl mt-3">
              Sesi kedua berada di gedung SD Lantai 4 (aula). Di sesi kedua ini,
              kami melakukan seminar tentan kepemimpinan dan diberi tahu makna
              dari game-game yang telah kami mainkan di sesi 1
            </p>
          </div>
        </div>
      </div>
      <div className="flex justify-between flex-row w-full h-screen bg-gray-900 px-8 py-28">
        <div>
          <p className="text-4xl lg:text-5xl font-bold text-gray-900 dark:text-gray-100">
            Sesi 2: 4C
          </p>
          <p className="text-xl text-gray-700 dark:text-gray-300 max-w-xl mt-3">
            Di sesi kedua ini kami juga dijelaskan tentang 4C. 4C adalah
            Collaboration, Communication, Critical Thinking, dan Creativity.
            Dengan 4C ini kami diajarkan untuk mau berkolaborasi, mau
            berkomunikasi, mau berpikir kritis serta memajukan kreativitas kami
          </p>
        </div>
        <Image src="/8.jpeg" width={680} height={300} alt="ok" />
      </div>
    </>
  );
};

export default materi;
