import React from "react";
import Head from "next/head";
import Image from "next/image";
import Navbar from "./Navbar";

const Penutup = () => {
  return (
    <>
      <Head>
        <title>Penutup | Kelompok 4</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="flex justify-between flex-row w-full h-screen bg-gray-900 px-8 py-28">
        <div>
          <p className="text-4xl lg:text-5xl font-bold text-gray-900 dark:text-gray-100">
            Hal yang didapat
          </p>
          <p className="text-xl text-gray-700 dark:text-gray-300 max-w-xl mt-3">
            Dengan adanya seminar ini, kami mendapatkan ilmu tentang
            kepemimpinan serta kami harap dapat menerapkannya, juga dapat
            menjadi pemimpin yang baik.
          </p>
        </div>
        <Image src="/9.jpeg" width={600} height={300} alt="ok" />
      </div>
      <div className="flex justify-between flex-row w-full h-screen bg-gray-900 px-8 py-28">
        <Image src="/10.jpeg" width={600} height={300} alt="ok" />

        <div>
          <p className="text-4xl lg:text-5xl font-bold text-gray-900 max-w-xl dark:text-gray-100">
            Pendapat
          </p>
          <p className="text-xl text-gray-700 dark:text-gray-300 max-w-xl mt-3">
            Menurut kami, seminar ini adalah seminar yang sangat bagus.
            Pembawaanya juga seru, dan ada games yang membuat kita tidak bosan
          </p>
        </div>
      </div>
      <div className="flex justify-between flex-row w-full h-screen bg-gray-900 px-8 py-28">
        <div>
          <p className="text-4xl lg:text-5xl font-bold text-gray-900 dark:text-gray-100">
            Kesimpulan
          </p>
          <p className="text-xl text-gray-700 dark:text-gray-300 max-w-xl mt-3">
            Kesimpulan dari seminar ini adalah kami mendapat banyak ilmu dan
            manfaat dari seminar ini, serta mengenal tentang kepemimpinan
          </p>
        </div>
        <Image src="/11.jpeg" width={600} height={300} alt="ok" />
      </div>
    </>
  );
};

export default Penutup;
